dmoj/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import include, path, re_path, reverse
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import sitemaps
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tag, tasks, ticket, \
    two_factor, user, widgets
from judge.views.magazine import MagazinePage
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, OrganizationUserSelect2View, ProblemSelect2View, \
    TagGroupSelect2View, TagSelect2View, TicketUserSelect2View, UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

SEND_ACTIVATION_EMAIL = getattr(settings, 'SEND_ACTIVATION_EMAIL', True)
REGISTRATION_COMPLETE_TEMPLATE = 'registration/registration_complete.html' if SEND_ACTIVATION_EMAIL \
                                 else 'registration/activation_complete.html'

register_patterns = [
    path('activate/complete/',
         TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title=_('Activation Successful!')),
         name='registration_activation_complete'),
    # Let's use <str:activation_key>, because a bad activation key should still get to the view;
    # that way, it can return a sensible "invalid key" message instead of a confusing 404.
    path('activate/<str:activation_key>/', ActivationView.as_view(), name='registration_activate'),
    path('register/', RegistrationView.as_view(), name='registration_register'),
    path('register/complete/',
         TitledTemplateView.as_view(template_name=REGISTRATION_COMPLETE_TEMPLATE,
                                    title=_('Registration Completed')),
         name='registration_complete'),
    path('register/closed/',
         TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title=_('Registration Not Allowed')),
         name='registration_disallowed'),
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
        title=_('Password change successful'),
    ), name='password_change_done'),
    path('password/reset/', user.CustomPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/password_reset_confirm.html',
                title=_('Enter new password'),
            ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
        title=_('Password reset complete'),
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
        title=_('Password reset sent'),
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),

    path('2fa/', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    path('2fa/enable/', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    path('2fa/refresh/', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    path('2fa/disable/', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    path('2fa/webauthn/attest/', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    path('2fa/webauthn/assert/', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    path('2fa/webauthn/delete/<int:pk>', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    path('2fa/scratchcode/generate/', user.generate_scratch_codes, name='generate_scratch_codes'),

    path('api/token/generate/', user.generate_api_token, name='generate_api_token'),
    path('api/token/remove/', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),

    path('problems', include([
        path('/', problem.ProblemList.as_view(), name='problem_list'),
        path('/random/', problem.RandomProblem.as_view(), name='problem_random'),
        path('/suggest_list/', problem.SuggestList.as_view(), name='problem_suggest_list'),
        path('/suggest', problem.ProblemSuggest.as_view(), name='problem_suggest'),
        path('/create', problem.ProblemCreate.as_view(), name='problem_create'),
        path('/import-polygon', problem.ProblemImportPolygon.as_view(), name='problem_import_polygon'),
    ])),

    path('problem/<str:problem>', include([
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/edit', problem.ProblemEdit.as_view(), name='problem_edit'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/raw', xframe_options_sameorigin(problem.ProblemRaw.as_view()), name='problem_raw'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<int:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/update-polygon', problem.ProblemUpdatePolygon.as_view(), name='problem_update_polygon'),

        path('/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<path:path>', problem_data_file, name='problem_data_file'),

        path('/tickets/', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                 name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                 name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                 name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                 name='problem_submissions_rescore_success'),
        ])),
    ])),

    path('tags', include([
        path('/', tag.TagProblemList.as_view(), name='tagproblem_list'),
        path('/create', tag.TagProblemCreate.as_view(), name='tagproblem_create'),
        path('/random/', tag.TagRandomProblem.as_view(), name='tagproblem_random'),
        path('/find', tag.TagFindProblem.as_view(), name='tagproblem_find'),
    ])),

    path('tag/<str:tagproblem>', include([
        path('', tag.TagProblemDetail.as_view(), name='tagproblem_detail'),
        path('/assign', tag.TagProblemAssign.as_view(), name='tagproblem_assign'),
        path('/', lambda _, tagproblem: HttpResponsePermanentRedirect(reverse('tagproblem_detail', args=[tagproblem]))),
    ])),

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class GeneralIssue(models.Model):
    issue_url = models.URLField(max_length=200, verbose_name=('Link to the issue'))

    def get_absolute_url(self):
        return self.issue_url

    def __str__(self):
        return self.issue_url


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_contributive = models.BooleanField(verbose_name=_('is ticket contributive?'), default=False)
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('user'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/problem/editor.html
{% extends "base.html" %}

{% block js_media %}
    {{ form.media.js }}
    {% include "leave-warning.html" %}

    <script src="{{ static('vnoj/jquery.formset.js') }}"></script>

    <script>
        $(function() {
            {% if lang_limit_formset %}
                $('#form_set tr').formset({
                    prefix: '{{ lang_limit_formset.prefix }}'
                });

            $('#lang_limit_title').click(function() {
                $('#lang_limit_title i').toggleClass('fa-caret-down fa-caret-up');
                $('#lang_limit_table').toggleClass('hidden');
            });
            $('#lang_limit_title').click();
            {% endif %}

            var noResults = function () {
                return {{ _('Press Enter to select multiple users...')|htmltojs }};
            };

            $(document).one('click', '#id_testers + .select2', function (e) {
                $('#id_testers').data().select2.options.get('translations').dict['noResults'] = noResults;
            });

            $(document).on('keyup', '#id_testers + .select2 .select2-search__field', function (e) {
                if (e.keyCode === 13) {
                    var $id_testers = $('#id_testers');
                    var testers = $(this).val().split(/[\s,]+/);
                    if (testers.length <= 1) {
                        // Skip to let select2 handle this
                        return;
                    }

                    $.ajax({
                        type: 'GET',
                        url: $id_testers.data().select2.dataAdapter.ajaxOptions.url,
                        data: {
                            multiple_terms: testers,
                        },
                        success: function (response) {
                            for (const tester of response.results) {
                                $id_testers.select2('trigger', 'select', {
                                    data: tester,
                                });
                            }
                        },
                    });
                }
            });
        })
    </script>
{% endblock %}

{% block media %}
    {{ form.media.css }}
    <link rel="stylesheet" type="text/css" href="{{ static('ui_form.css') }}">
    <style>
        .hidden {
            display: none;
        }
    </style>
{% endblock %}

{% macro form_as_row(form) -%}
    {% if form.non_field_errors() %}
    <tr>
        <td colspan="6">{{ form.non_field_errors() }}</td>
    </tr>
    {% endif %}
    <tr>
        <td>{{ form.id }} {{ form.language.errors }}{{ form.language }}</td>
        <td>{{ form.time_limit.errors }}{{ form.time_limit }}</td>
        <td>{{ form.memory_limit.errors }}{{ form.memory_limit }}</td>
        <td>
        {% if lang_limit_formset.can_delete and form.instance.pk %}
            {{ form.DELETE }}
        {% endif %}
        </td>
    <tr>
{%- endmacro %}

{% block body %}
<div>
    {% if request.user.is_staff %}
        <div class="alert alert-warning alert-dismissable">
            <a class="close">x</a>
            <a href="{{ url('admin:judge_problem_change', object.id) }}">{{ _('Edit problem in admin panel for more options') }}</a>
        </div>
    {% endif %}
    {% if perms.judge.import_polygon_package %}
        <div class="alert alert-warning alert-dismissable">
            <a class="close">x</a>
            <a href="{{ url('problem_update_polygon', object.code) }}">{{ _('Update problem from Codeforces Polygon package') }}</a>
        </div>
    {% endif %}
    <form action="" method="post" class="form-area" enctype="multipart/form-data" style="display: flex; justify-content: center; flex-direction: column;">
        {% if form.errors or solution_formset.errors %}
            <p class="errornote"> {{ _('Please correct the error below.') }}</p>
        {% endif %}
        {% csrf_token %}
        {{ lang_limit_formset.management_form }}
        <table class="django-as-table">{{ form.as_table() }}</table>
        <hr>

        <center>
            <h3 id="lang_limit_title">{{ _('Language-specific resource limit') }} <i class="fa fa-caret-up"></i></h3>
            <span class="helptext">{{ _('Only use this feature if you really need to!') }}</span>
        </center>
        <table class="table" id="lang_limit_table">
            <thead>
                <tr>
                    <th style="width: 20em;"> {{ _('Language') }} </th>
                    <th> {{ _('Time limit (seconds)') }} </th>
                    <th> {{ _('Memory limit (KiB)') }} </th>
                    <th> {{ _('Delete') }} </th>
                </tr>
            </thead>
            <tbody id="form_set">
                {% for form in lang_limit_formset %}
                    {{ form_as_row(form) }}
                {% endfor %}
            </tbody>
        </table>
        <hr>

        <center><h3> {{ _('Editorial') }} </h3></center>
        <table class="django-as-table">{{ solution_formset.as_table() }}</table>

        <table>
            <tr><td style="float: left;">
            <td style="float: right;"><input type="submit" value="{{ _('Update') }}" class="button"></td></tr>
        </table>
    </form>
</div>
{% endblock %}

templates/problem/editorial.html
{% extends "common-content.html" %}

{% block content_js_media %}
    {% include "comments/media-js.html" %}
{% endblock %}

{% block content_media %}
    {% include "comments/media-css.html" %}
{% endblock %}

{% block header %}
    <div style="float:right">
        {% if problem.is_editable_by(request.user) %}
            [<a href="{{ url('admin:judge_problem_change', problem.id) }}">{{ _('Edit') }}</a>]
        {% endif %}
    </div>
{% endblock %}

{% block body %}
    <div class="content-description">
        {% if not has_solved_problem %}
            <div class="alert alert-danger">
                {{ _('Remember to use this editorial **only** when stuck, and **not to copy-paste code from it**. Please be respectful to the problem author and editorialist.')|markdown('default', strip_paragraphs=True) }}<br>
                <b>{{ _('Submitting an official solution before solving the problem yourself is a bannable offence.') }}</b>
            </div>
        {% endif %}
        {% with authors=solution.authors.all() %}
            {% if authors %}
                <p>
                    {% trans trimmed count=authors|length %}
                        Author: 
                    {% pluralize %}
                        Authors: 
                    {% endtrans %}
                    {{ link_users(authors) }}
                </p>
            {% endif %}
        {% endwith %}
        {{ solution.content|markdown('solution', MATH_ENGINE)|reference|str|safe }}
    </div>
    <hr>
    {% include "comments/list.html" %}
{% endblock %}

{% block bodyend %}
    {% if REQUIRE_JAX %}
        {% include "mathjax-load.html" %}
    {% endif %}
{% endblock %}

templates/problem/manage_submission.html
{% extends "base.html" %}

{% block media %}
    {{ form_compare.media.css }}
    <style>
        .panes {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .pane {
            display: block;
            max-width: 20em;
            border: 1px #ccc solid;
            border-radius: 5px;
            padding: 10px;
            margin: 10px;
        }

        .pane h3 {
            display: block;
            background: #3b3b3b;
            padding: 5px 10px 10px;
            margin: -10px -10px 10px;
            border-radius: 5px 5px 0 0;
            color: white;
        }

        .control-group {
            margin: 1em 0;
        }

        .control-group:not(:first-of-type) {
            border-top: 1px solid #ccc;
            padding-top: 0.5em;
        }

        .control-group label {
            display: block;
            margin-bottom: 0.5em;
        }

        .control-group select {
            display: block;
            width: 100%;
        }
    </style>
{% endblock %}

{% block js_media %}
    {{ form_compare.media.js }}
    <script>
        $(function () {
            $('#by-lang-filter').select2({
                theme: '{{ DMOJ_SELECT2_THEME }}',
                multiple: true,
                placeholder: {{ _('Leave empty to not filter by language')|htmltojs }}
            });

            $('#by-result-filter').select2({
                theme: '{{ DMOJ_SELECT2_THEME }}',
                multiple: true,
                placeholder: {{ _('Leave empty to not filter by result')|htmltojs }}
            });

            $('#rescore-all').click(function (e) {
                e.preventDefault();
                if (confirm(this.dataset.warning)) {
                    $(this).parents('form').submit();
                }
            });

            $('#compare').click(function (e) {
                e.preventDefault();
                var usernames = $("#id_user option:selected").toArray().map(item => item.text);
                if (usernames.length === 0) {
                    alert({{ _('Please select at least one user.')|htmltojs }});
                    return;
                }

                var qs = usernames.map(item => 'username=' + item).join('&');
                window.location.href = '{{ url('problem_submission_diff', problem.code) }}?' + qs;
            });

            var $use_id = $('#by-range-check');
            var $id_start = $('#by-range-start');
            var $id_end = $('#by-range-end');
            $('#rejudge-selected').click(function (e) {
                e.preventDefault();
                if ($use_id.prop('checked')) {
                    var start = parseInt($id_start.val());
                    var end = parseInt($id_end.val());
                    if (!start || !end) {
                        alert({{ _('Need valid values for both start and end IDs.')|htmltojs }});
                        return;
                    } else if (start > end) {
                        alert({{ _('End ID must be after start ID.')|htmltojs }});
                        return;
                    }
                }

                var $form = $(this).parents('form');
                $.post('{{ url('problem_submissions_rejudge_preview', problem.code) }}', $form.serialize(), 'text')
                    .done(function (count) {
                        if (confirm({{ _('You are about to rejudge {count} submissions. Are you sure you want to do this?')|htmltojs }}
                            .replace('{count}', count))) {
                            $form.submit();
                        }
                    })
                    .fail(function () {
                        if (confirm({{ _('You are about to rejudge a few submissions. Are you sure you want to do this?')|htmltojs }})) {
                            $form.submit();
                        }
                    });
            });

            $use_id.change(function () {
                $('#by-range-filter').find('input').prop('disabled', !this.checked);
            });
        });
    </script>
{% endblock %}

{% block body %}
    {% include "messages.html" %}

    <div class="panes">
        {% if request.user.has_perm('judge.rejudge_submission_lot') %}
            <div class="pane">
                <h3>{{ _('Rejudge Submissions') }}</h3>
                <form action="{{ url('problem_submissions_rejudge', problem.code) }}" method="post">
                    {% csrf_token %}
                    <div class="control-group">
                        <label><input id="by-range-check" type="checkbox" name="use_range" value="on">
                            {{ _('Filter by ID:') }}</label>
                        <table id="by-range-filter" class="table">
                            <tr>
                                <th><label for="by-range-start">{{ _('Starting ID:') }}</label></th>
                                <td><input id="by-range-start" name="start" type="number" disabled></td>
                            </tr>
                            <tr>
                                <th><label for="by-range-end">{{ _('Ending ID:') }}</label></th>
                                <td><input id="by-range-end" name="end" type="number" disabled></td>
                            </tr>
                        </table>
                        <p>{{ _('This range includes both endpoints.') }}</p>
                    </div>
                    <div class="control-group">
                        <label for="by-lang-filter">{{ _('Filter by language:') }}</label>
                        <select id="by-lang-filter" name="language" multiple>
                            {% for id, name in languages %}
                                <option value="{{ id }}">{{ name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="control-group">
                        <label for="by-result-filter">{{ _('Filter by result:') }}</label>
                        <select id="by-result-filter" name="result" multiple>
                            {% for name in results %}
                                <option>{{ name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <a id="rejudge-selected" class="unselectable button full" href="#">
                        {{ _('Rejudge selected submissions') }}
                    </a>
                </form>
            </div>
        {% endif %}

        <div class="pane">
            <h3>{{ _('Rescore Everything') }}</h3>
            <p id="rescore-warning">{% trans trimmed count=submission_count %}
                This will rescore {{ count }} submission.
            {% pluralize %}
                This will rescore {{ count }} submissions.
            {% endtrans %}</p>
            <form action="{{ url('problem_submissions_rescore_all', problem.code) }}" method="post">
                {% csrf_token %}
                <a id="rescore-all" class="unselectable button full" href="#"
                   data-warning="{% trans trimmed count=submission_count %}
                                    Are you sure you want to rescore {{ count }} submission?
                                 {% pluralize %}
                                    Are you sure you want to rescore {{ count }} submissions?
                                 {% endtrans %}">
                    {{ _('Rescore all submissions') }}
                </a>
            </form>
        </div>

        <div class="pane">
            <h3>{{ _('Compare Submissions') }}</h3>
            <div class="control-group">
                <label for="id_user">{{ _('Filter by user:') }}</label>
                {{ form_compare.user }}
            </div>
            <a id="compare" class="unselectable button full" href="#">
                {{ _('Compare submissions') }}
            </a>
        </div>
    </div>
{% endblock %}

templates/problem/preview.html
{{ preview_data|markdown('problem', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/problem/problem-list-tabs.html
{% extends "tabs-base.html" %}

{% block tabs %}
    {% if request.user.has_perm('judge.add_problem') %}
        {{ make_tab('create', 'fa-plus', url('problem_create'), _('Create new problem')) }}
    {% elif request.user.has_perm('judge.suggest_new_problem') %}
        {{ make_tab('suggest', 'fa-plus', url('problem_suggest'), _('Suggest new problem')) }}
    {% endif %}
    {{ make_tab('list', 'fa-list', url('problem_list'), _('List')) }}

    {% if perms.judge.edit_all_problem or perms.judge.edit_public_problem or perms.judge.edit_own_problem %}
        {{ make_tab('suggest', 'fa-list', url('problem_suggest_list'), _('Suggest')) }}
    {% endif %}
    {% if request.user.is_superuser %}
        {{ make_tab('admin', 'fa-edit', url('admin:judge_problem_changelist'), _('Admin')) }}
    {% endif %}
{% endblock %}

templates/problem/suggest-list.html
{% extends 'problem/list.html' %}

{% block title_row %}
    {% set tab = 'suggest' %}
    {% include "problem/problem-list-tabs.html" %}
{% endblock %}