dmoj/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import include, path, re_path, reverse
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import sitemaps
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tag, tasks, ticket, \
    two_factor, user, widgets
from judge.views.magazine import MagazinePage
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, OrganizationUserSelect2View, ProblemSelect2View, \
    TagGroupSelect2View, TagSelect2View, TicketUserSelect2View, UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

SEND_ACTIVATION_EMAIL = getattr(settings, 'SEND_ACTIVATION_EMAIL', True)
REGISTRATION_COMPLETE_TEMPLATE = 'registration/registration_complete.html' if SEND_ACTIVATION_EMAIL \
                                 else 'registration/activation_complete.html'

register_patterns = [
    path('activate/complete/',
         TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title=_('Activation Successful!')),
         name='registration_activation_complete'),
    # Let's use <str:activation_key>, because a bad activation key should still get to the view;
    # that way, it can return a sensible "invalid key" message instead of a confusing 404.
    path('activate/<str:activation_key>/', ActivationView.as_view(), name='registration_activate'),
    path('register/', RegistrationView.as_view(), name='registration_register'),
    path('register/complete/',
         TitledTemplateView.as_view(template_name=REGISTRATION_COMPLETE_TEMPLATE,
                                    title=_('Registration Completed')),
         name='registration_complete'),
    path('register/closed/',
         TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title=_('Registration Not Allowed')),
         name='registration_disallowed'),
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
        title=_('Password change successful'),
    ), name='password_change_done'),
    path('password/reset/', user.CustomPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/password_reset_confirm.html',
                title=_('Enter new password'),
            ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
        title=_('Password reset complete'),
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
        title=_('Password reset sent'),
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),

    path('2fa/', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    path('2fa/enable/', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    path('2fa/refresh/', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    path('2fa/disable/', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    path('2fa/webauthn/attest/', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    path('2fa/webauthn/assert/', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    path('2fa/webauthn/delete/<int:pk>', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    path('2fa/scratchcode/generate/', user.generate_scratch_codes, name='generate_scratch_codes'),

    path('api/token/generate/', user.generate_api_token, name='generate_api_token'),
    path('api/token/remove/', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),

    path('problems', include([
        path('/', problem.ProblemList.as_view(), name='problem_list'),
        path('/random/', problem.RandomProblem.as_view(), name='problem_random'),
        path('/suggest_list/', problem.SuggestList.as_view(), name='problem_suggest_list'),
        path('/suggest', problem.ProblemSuggest.as_view(), name='problem_suggest'),
        path('/create', problem.ProblemCreate.as_view(), name='problem_create'),
        path('/import-polygon', problem.ProblemImportPolygon.as_view(), name='problem_import_polygon'),
    ])),

    path('problem/<str:problem>', include([
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/edit', problem.ProblemEdit.as_view(), name='problem_edit'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/raw', xframe_options_sameorigin(problem.ProblemRaw.as_view()), name='problem_raw'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<int:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/update-polygon', problem.ProblemUpdatePolygon.as_view(), name='problem_update_polygon'),

        path('/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<path:path>', problem_data_file, name='problem_data_file'),

        path('/tickets/', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                 name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                 name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                 name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                 name='problem_submissions_rescore_success'),
        ])),
    ])),

    path('tags', include([
        path('/', tag.TagProblemList.as_view(), name='tagproblem_list'),
        path('/create', tag.TagProblemCreate.as_view(), name='tagproblem_create'),
        path('/random/', tag.TagRandomProblem.as_view(), name='tagproblem_random'),
        path('/find', tag.TagFindProblem.as_view(), name='tagproblem_find'),
    ])),

    path('tag/<str:tagproblem>', include([
        path('', tag.TagProblemDetail.as_view(), name='tagproblem_detail'),
        path('/assign', tag.TagProblemAssign.as_view(), name='tagproblem_assign'),
        path('/', lambda _, tagproblem: HttpResponsePermanentRedirect(reverse('tagproblem_detail', args=[tagproblem]))),
    ])),

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class GeneralIssue(models.Model):
    issue_url = models.URLField(max_length=200, verbose_name=('Link to the issue'))

    def get_absolute_url(self):
        return self.issue_url

    def __str__(self):
        return self.issue_url


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_contributive = models.BooleanField(verbose_name=_('is ticket contributive?'), default=False)
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('user'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/comments/base-media-js.html
<script src="{{ static('libs/featherlight/featherlight.min.js') }}" type="text/javascript"></script>

<script type="text/javascript">
    function rename_martor_widget(widget, old_name, new_name) {
        function rename_data(data_name, prefix) {
            widget.find('[data-' + data_name + '=' + prefix + old_name + ']')
                  .data(data_name, prefix + new_name)
                  .attr('data-' + data_name, prefix + new_name);
        }
        function rename_id(prefix) {
            widget.find('#' + prefix + old_name).prop('id', prefix + new_name);
        }
        function rename_class(prefix) {
            widget.find('.' + prefix + old_name).removeClass(prefix + old_name).addClass(prefix + new_name);
        }
        rename_data('tab', 'editor-tab-');
        rename_data('tab', 'preview-tab-');
        rename_data('field-name', '');
        rename_id('id_');
        rename_id('martor-');
        rename_class('martor-field-');
        rename_class('main-martor-');
        widget.find('.main-martor').martor();
    }

    $(document).ready(function () {
        window.reply_comment = function (parent) {
            var $comment_reply = $('#comment-' + parent + '-reply');
            var reply_id = 'reply-' + parent;
            if ($comment_reply.find('#' + reply_id).length == 0) {
                var $reply_form = $('#new-comment').clone(false).prop('id', reply_id);
                $reply_form.find('h3').html({{ _('Replying to comment')|htmltojs }});
                $reply_form.prepend('<a class="close">x</a>');
                $reply_form.appendTo($comment_reply);
                $reply_form.find('form.comment-submit-form input#id_parent').val(parent);
                rename_martor_widget($reply_form, 'body', reply_id);
                ace.edit('martor-' + reply_id).setValue('');
            }
            $comment_reply.fadeIn();

            $('html, body').animate({
                scrollTop: $comment_reply.offset().top - $('#navigation').height() - 4
            }, 500);
        };

        $(document).on('click', '.close', function() {
            $(this).closest('.reply-comment').fadeOut();
        });

        function update_math($comment) {
            if ('MathJax' in window) {
                var $body = $comment.find('.comment-body');
                MathJax.typesetPromise([$body[0]]).then(function () {
                    $body.find('.tex-image').hide();
                    $body.find('.tex-text').show();
                });
            }
        }

        window.show_revision = function (comment_id, offset) {
            var $comment = $("#comment-" + comment_id);

            // If .comment-body is hidden, then this is a bad comment that the user has not clicked
            // Thus the revision retrieval should do nothing
            if (!$comment.find('.comment-body').is(':visible'))
                return;

            var cur_revision = parseInt($comment.attr("data-revision"));
            var max_revision = parseInt($comment.attr("data-max-revision"));
            var revision_ajax = $comment.attr("data-revision-ajax");
            var show_revision = cur_revision + offset;

            // Do nothing if desired revision is out of bounds
            if (show_revision < 0 || show_revision > max_revision)
                return;

            $comment.attr("data-revision", show_revision);

            $.get(revision_ajax, {
                revision: show_revision
            }).done(function (body) {
                $comment.find('.previous-revision').css({visibility: show_revision == 0 ? 'hidden' : ''});
                $comment.find('.next-revision').css({visibility: show_revision == max_revision ? 'hidden' : ''});
                var $content = $comment.find('.content').html(body);

                var edit_text = {{ _('edit {edits}')|htmltojs }}.replace("{edits}", show_revision);

                if (show_revision == 0) {
                    edit_text = {{ _('original')|htmltojs }};
                } else if (show_revision == max_revision && max_revision == 1) {
                    edit_text = {{ _('edited')|htmltojs }};
                }

                $comment.find('.comment-edit-text').text(' ' + edit_text + ' ');
                update_math($content);
                if (window.add_code_copy_buttons)
                    window.add_code_copy_buttons($content);
            });
        };

        function ajax_vote(url, id, delta, on_success) {
            return $.ajax({
                url: url,
                type: 'POST',
                data: {
                    id: id
                },
                success: function (data, textStatus, jqXHR) {
                    var score = $('#comment-' + id + ' .comment-score').first();
                    score.text(parseInt(score.text()) + delta);
                    if (typeof on_success !== 'undefined')
                        on_success();
                },
                error: function (data, textStatus, jqXHR) {
                    alert({{ _('Could not vote: {error}')|htmltojs }}.replace('{error}', data.responseText));
                }
            });
        }

        var get_$votes = function (id) {
            var $comment = $('#comment-' + id);
            return {
                upvote: $comment.find('.upvote-link').first(),
                downvote: $comment.find('.downvote-link').first()
            };
        };

        window.comment_upvote = function (id) {
            ajax_vote('{{ url('comment_upvote') }}', id, 1, function () {
                var $votes = get_$votes(id);
                if ($votes.downvote.hasClass('voted'))
                    $votes.downvote.removeClass('voted');
                else
                    $votes.upvote.addClass('voted');
            });
        };

        window.comment_downvote = function (id) {
            ajax_vote('{{ url('comment_downvote') }}', id, -1, function () {
                var $votes = get_$votes(id);
                if ($votes.upvote.hasClass('voted'))
                    $votes.upvote.removeClass('voted');
                else
                    $votes.downvote.addClass('voted');
            });
        };

        var $comments = $('.comments');
        $comments.find('a.hide-comment').click(function (e) {
            e.preventDefault();
            if (!(e.ctrlKey || e.metaKey || confirm({{ _('Are you sure you want to hide this comment?')|htmltojs }})))
                return;

            var id = $(this).attr('data-id');
            $.post('{{ url('comment_hide') }}', {id: id}).then(function () {
                $('#comment-' + id).remove();
                $('#comment-' + id + '-children').remove();
            }).catch(function () {
                alert({{ _('Could not hide comment.')|htmltojs }});
            });
        });

        $comments.find('a.edit-link').featherlight({
            afterOpen: function () {
                var $widget = $('.featherlight #comment-form-body');
                rename_martor_widget($widget, 'body', 'edit');
                $('#comment-edit').submit(function (event) {
                    event.preventDefault();
                    var id = $('#comment-edit').find('.comment-id').text();
                    var readback = $('#comment-edit').find('.read-back').text();
                    $.post($(this).attr('action'), $(this).serialize()).done(function (data) {
                        $.featherlight.current().close();
                        $.ajax({
                            url: readback
                        }).done(function (data) {
                            var $comment = $('#comment-' + id);
                            var $area = $comment.find('.comment-body').first();
                            $area.html(data);
                            update_math($comment);
                            if (window.add_code_copy_buttons)
                                window.add_code_copy_buttons($area);
                            var $edits = $comment.find('.comment-edits').first();
                            $edits.text({{ _('updated')|htmltojs }});
                        }).fail(function () {
                            alert({{ _('Failed to update comment body.')|htmltojs }});
                        });
                    }).fail(function (data) {
                            alert({{ _('Could not edit comment: {error}')|htmltojs }}.replace('{error}', data.responseText));
                    });
                });
            },
            variant: 'featherlight-edit'
        });

        $('votes-link').find('a[data-featherlight]').featherlight();

        var $root = $('html, body');
        $comments.find('a.comment-link').click(function () {
            var href = $.attr(this, 'href');
            $root.animate({
                scrollTop: $(href).offset().top
            }, 500, function () {
                window.location.hash = href;
            });
            return false;
        });

        $('img.unveil').unveil(200);

        window.comment_show_content = function (comment_id) {
            var $comment = $('#comment-' + comment_id);
            $comment.find('.comment-body').show();
            $comment.find('.bad-comment-body').hide();
        };

        var code_regex = [/#include\s*<.+>/, /using\s+namespace/, /int\s+main/, /print\s*\(.+\)/];
        $(document).on('click', 'form.comment-submit-form .button[type=submit]', async function (e) {
            var form = $(this).parents('form');
            var text = form.find('#id_body').val();
            if (code_regex.some(regex => regex.test(text))) {
                if (!confirm(`{{ _('Looks like you\'re trying to post a source code!\n\nThe comment section are not for posting source code.\nIf you want to submit your solution, please use the "Submit solution" button.\n\nAre you sure you want to post this?') }}`)) {
                    e.preventDefault();
                }
            }
        });
    });
</script>

templates/comments/content.html
{{ comment.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}

templates/comments/edit-ajax.html
<div class="comment-submit comment-edit-form">
    <form id="comment-edit" action="{{ request.get_full_path() }}" method="post">
        <span style="display: none" class="comment-id">{{ comment.id }}</span>
        <span style="display: none" class="read-back">{{ url('comment_content', comment.id) }}</span>
        {% csrf_token %}
        {% if form.non_field_errors() or form.body.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="comment-post-wrapper">
            <div id="comment-form-body">{{ form.body }}</div>
        </div>
        <hr>
        <input style="float: right" type="submit" value="{{ _('Post!') }}" class="button">
    </form>
</div>

templates/comments/edit.html
{% extends "base.html" %}
{% block media %}
    {% compress css %}
        {{ form.media.css }}
    {% endcompress %}
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
{% endblock %}
{% block body %}
    <div class="form-area">{% include "comments/edit-ajax.html" %}</div>
{% endblock %}

templates/comments/media-css.html
{% compress css %}
    {{ comment_form.media.css }}
{% endcompress %}

templates/comments/media-js.html
{% compress js %}
    {{ comment_form.media.js }}
    {% include "comments/base-media-js.html" %}
{% endcompress %}

templates/comments/preview.html
{{ preview_data|markdown('comment', MATH_ENGINE)|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/comments/revision-ajax.html
{% with node=revision.field_dict %}
    <div class="comment-body">{{ node.body|markdown('comment', MATH_ENGINE)|reference|str|safe }}</div>
{% endwith %}

templates/comments/votes.html
<h2 style="text-align: center">{{ _('Votes') }}</h2>
<table class="table striped">
    <thead>
    <tr>
        <th>{{ _('Voter') }}</th>
        <th>{{ _('Score') }}</th>
    </tr>
    </thead>
    <tbody>
    {% for vote in votes %}
        <tr>
            <td>{{ link_user(vote.voter) }}</td>
            <td>{{ vote.score }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="2">{{ _('No votes') }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>