dmoj/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.templatetags.static import static
from django.urls import include, path, re_path, reverse
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.generic import RedirectView
from martor.views import markdown_search_user

from judge.feed import AtomBlogFeed, AtomCommentFeed, AtomProblemFeed, BlogFeed, CommentFeed, ProblemFeed
from judge.sitemap import sitemaps
from judge.views import TitledTemplateView, api, blog, comment, contests, language, license, mailgun, organization, \
    preview, problem, problem_manage, ranked_submission, register, stats, status, submission, tag, tasks, ticket, \
    two_factor, user, widgets
from judge.views.magazine import MagazinePage
from judge.views.problem_data import ProblemDataView, ProblemSubmissionDiff, \
    problem_data_file, problem_init_view
from judge.views.register import ActivationView, RegistrationView
from judge.views.select2 import AssigneeSelect2View, CommentSelect2View, ContestSelect2View, \
    ContestUserSearchSelect2View, OrganizationSelect2View, OrganizationUserSelect2View, ProblemSelect2View, \
    TagGroupSelect2View, TagSelect2View, TicketUserSelect2View, UserSearchSelect2View, UserSelect2View
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

SEND_ACTIVATION_EMAIL = getattr(settings, 'SEND_ACTIVATION_EMAIL', True)
REGISTRATION_COMPLETE_TEMPLATE = 'registration/registration_complete.html' if SEND_ACTIVATION_EMAIL \
                                 else 'registration/activation_complete.html'

register_patterns = [
    path('activate/complete/',
         TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title=_('Activation Successful!')),
         name='registration_activation_complete'),
    # Let's use <str:activation_key>, because a bad activation key should still get to the view;
    # that way, it can return a sensible "invalid key" message instead of a confusing 404.
    path('activate/<str:activation_key>/', ActivationView.as_view(), name='registration_activate'),
    path('register/', RegistrationView.as_view(), name='registration_register'),
    path('register/complete/',
         TitledTemplateView.as_view(template_name=REGISTRATION_COMPLETE_TEMPLATE,
                                    title=_('Registration Completed')),
         name='registration_complete'),
    path('register/closed/',
         TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title=_('Registration Not Allowed')),
         name='registration_disallowed'),
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
        title=_('Password change successful'),
    ), name='password_change_done'),
    path('password/reset/', user.CustomPasswordResetView.as_view(), name='password_reset'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                template_name='registration/password_reset_confirm.html',
                title=_('Enter new password'),
            ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
        title=_('Password reset complete'),
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
        title=_('Password reset sent'),
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),

    path('2fa/', two_factor.TwoFactorLoginView.as_view(), name='login_2fa'),
    path('2fa/enable/', two_factor.TOTPEnableView.as_view(), name='enable_2fa'),
    path('2fa/refresh/', two_factor.TOTPRefreshView.as_view(), name='refresh_2fa'),
    path('2fa/disable/', two_factor.TOTPDisableView.as_view(), name='disable_2fa'),
    path('2fa/webauthn/attest/', two_factor.WebAuthnAttestationView.as_view(), name='webauthn_attest'),
    path('2fa/webauthn/assert/', two_factor.WebAuthnAttestView.as_view(), name='webauthn_assert'),
    path('2fa/webauthn/delete/<int:pk>', two_factor.WebAuthnDeleteView.as_view(), name='webauthn_delete'),
    path('2fa/scratchcode/generate/', user.generate_scratch_codes, name='generate_scratch_codes'),

    path('api/token/generate/', user.generate_api_token, name='generate_api_token'),
    path('api/token/remove/', user.remove_api_token, name='remove_api_token'),
]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),

    path('problems', include([
        path('/', problem.ProblemList.as_view(), name='problem_list'),
        path('/random/', problem.RandomProblem.as_view(), name='problem_random'),
        path('/suggest_list/', problem.SuggestList.as_view(), name='problem_suggest_list'),
        path('/suggest', problem.ProblemSuggest.as_view(), name='problem_suggest'),
        path('/create', problem.ProblemCreate.as_view(), name='problem_create'),
        path('/import-polygon', problem.ProblemImportPolygon.as_view(), name='problem_import_polygon'),
    ])),

    path('problem/<str:problem>', include([
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/edit', problem.ProblemEdit.as_view(), name='problem_edit'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/raw', xframe_options_sameorigin(problem.ProblemRaw.as_view()), name='problem_raw'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<int:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/update-polygon', problem.ProblemUpdatePolygon.as_view(), name='problem_update_polygon'),

        path('/rank/', paged_list_view(ranked_submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<path:path>', problem_data_file, name='problem_data_file'),

        path('/tickets/', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                 name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                 name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                 name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                 name='problem_submissions_rescore_success'),
        ])),
    ])),

    path('tags', include([
        path('/', tag.TagProblemList.as_view(), name='tagproblem_list'),
        path('/create', tag.TagProblemCreate.as_view(), name='tagproblem_create'),
        path('/random/', tag.TagRandomProblem.as_view(), name='tagproblem_random'),
        path('/find', tag.TagFindProblem.as_view(), name='tagproblem_find'),
    ])),

    path('tag/<str:tagproblem>', include([
        path('', tag.TagProblemDetail.as_view(), name='tagproblem_detail'),
        path('/assign', tag.TagProblemAssign.as_view(), name='tagproblem_assign'),
        path('/', lambda _, tagproblem: HttpResponsePermanentRedirect(reverse('tagproblem_detail', args=[tagproblem]))),
    ])),

judge/models/tag.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class TagGroup(models.Model):
    code = models.CharField(max_length=30, verbose_name=_('Tag group ID'), unique=True)
    name = models.CharField(max_length=100, verbose_name=_('Tag group name'))

    def __str__(self):
        return self.name


class Tag(models.Model):
    code = models.CharField(max_length=30, verbose_name=_('Tag ID'), unique=True, db_index=True)
    name = models.CharField(max_length=100, verbose_name=_('Tag name'), db_index=True)
    group = models.ForeignKey(TagGroup, related_name='tags', verbose_name=_('Parent tag group'), on_delete=CASCADE)

    def __str__(self):
        return self.name


class TagProblem(models.Model):
    code = models.CharField(max_length=32, verbose_name=_('problem code'), unique=True, db_index=True,
                            validators=[RegexValidator('^[a-zA-Z0-9_]+$', _('Problem code must be ^[a-zA-Z0-9_]+$'))],
                            help_text=_('A short, unique code for the problem, '
                                        'used in the url after /tag/'))
    name = models.CharField(max_length=100, verbose_name=_('problem name'), db_index=True,
                            help_text=_('The full name of the problem, '
                                        'as shown in the problem list.'))
    link = models.URLField(max_length=200, verbose_name=_('Problem URL'),
                           help_text=_('Full URL to the problem.'))
    judge = models.CharField(max_length=30, verbose_name=_('Online Judge'), blank=True, null=True, db_index=True,
                             help_text=_('Original OJ of the problem'))

    tag = models.ManyToManyField(Tag, through='TagData', related_name='tags', verbose_name=_('Tag'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tagproblem_detail', args=(self.code,))


class TagData(models.Model):
    assigner = models.ForeignKey(Profile, verbose_name=_('Assigner'), on_delete=CASCADE)
    tag = models.ForeignKey(Tag, verbose_name=_('Tag'), on_delete=CASCADE)
    problem = models.ForeignKey(TagProblem, on_delete=CASCADE)

    class Meta:
        unique_together = ('tag', 'problem')

    def __str__(self):
        return ''

templates/tag/assign.html
{% extends "base.html" %}

{% block js_media %}
    <script>
        $(function () {
            $('#tags').select2({
                theme: '{{ DMOJ_SELECT2_THEME }}',
                closeOnSelect:false
            });

            $('body').on('click', '.select2-results__group', function() {
                $(this).siblings().toggle();
            });

            $('body').on('click', '.select2-selection__rendered', function() {
                $('.select2-results__group').click();
            });
        });
    </script>
{% endblock %}

{% block media %}
    <link rel="stylesheet" type="text/css" href="{{ static('ui_form.css') }}">
    <style>
        label[for="tags"] {
            padding-bottom: 0.25em;
            display: block;
        }

        .select2-container--default .select2-results > .select2-results__options {
            min-height: 50vh;
        }
    </style>
{% endblock %}

{% block body %}
    <div>
        <form action="" method="post" class="form-area" style="display: flex; justify-content: center; flex-direction: column;">
            {% csrf_token %}
            <label for="tags"><b>{{ _('Tags') }}</b></label>
            <span class="helptext">You can click on a group's name to show/hide that group.</span>
            <select id="tags" name="tags" multiple>
                {% for group in groups %}
                    <optgroup label="{{ group.name }}">
                        {% for tag in group.tags.all() %}
                            <option value={{ tag.code }}>{{ tag.name }}</option>
                        {% endfor %}
                    </optgroup>
                {% endfor %}
            </select>
            <hr>
            <table>
                <tr><td style="float: left;">
                <td style="float: right;"><input type="submit" value="{{ _('Assign') }}" class="button"></td></tr>
            </table>
        </form>
    </div>
{% endblock %}

templates/tag/create.html
{% extends "base.html" %}

{% block js_media %}
    {{ form.media.js }}
{% endblock %}

{% block media %}
    {{ form.media.css }}
    <link rel="stylesheet" type="text/css" href="{{ static('ui_form.css') }}">
{% endblock %}

{% block body %}
    <div class="alert alert-warning alert-dismissable">
        <a class="close">x</a>
        <b>{{ _('Creating new problem can take longer than usual!') }}</b>
        <br>
        {{ _('Due to API requests and cache optimization, creating problem can take longer than usual.') }}
        <br>{{ _('If no problem is created after 2 to 3 minutes, please open a ticket, or contact the admin for further information.') }}
    </div>
    <div>
        <form action="" method="post" class="form-area" style="display: flex; justify-content: center; flex-direction: column;">
            {% csrf_token %}
            <table class="django-as-table">{{ form.as_table() }}</table>
            <hr>
            <table>
                <tr><td style="float: left;">
                <td style="float: right;"><input type="submit" value="{{ _('Create') }}" class="button"></td></tr>
            </table>
        </form>
    </div>
{% endblock %}

templates/tag/list.html
{% extends "common-content.html" %}

{% macro make_tag_url(tag) -%}
<a href="{{ url('tagproblem_list') }}?tag_id={{ tag.code }}{% if tag_prefix %}&{{ tag_prefix }}{% endif %}" tag_id={{ tag.code }}>{{ tag.name }}</a>
{%- endmacro -%}

{% block media %}
    <style>
        .row-selected {
            background: #dff0d8;
        }

        #judges {
            width: 100%;
        }

        label[for="judge"] {
            padding-bottom: 0.25em;
            display: block;
        }
    </style>
{% endblock %}

{% block js_media %}
    <script type="text/javascript" src="{{ static('accordion.js') }}"></script>

    {% if selected_tag %}
        <script>
            $(function () {
                var el = $('.accordion .card-body a[tag_id={{ selected_tag }}]')[0];
                if (el) {
                    el = $(el);
                    el.parent().addClass('row-selected');
                    el.parent().parent().addClass('show');
                    el.parent().parent().slideDown(0);
                }
            });
        </script>
    {% else %}
        <script>
            $(function () {
                var el = $('.accordion .card-toggle')[0];
                if (el) {
                    el = $(el);
                    el.next().addClass('show');
                    el.next().slideDown(0);
                }
            });
        </script>
    {% endif %}
{% endblock %}

{% block title_ruler %}{% endblock %}

{% block title_row %}
    {% set tab = 'list' %}
    {% include "tag/tag-list-tabs.html" %}
{% endblock %}

{% block body %}
    {% if page_obj.has_other_pages() %}
        <div class="top-pagination-bar">{% include "list-pages.html" %}</div>
    {% endif %}

    <div id="common-content">
        {% block before_table %}{% endblock %}
        <div id="content-right" class="problems">
            <div>
                {% include "tag/search-form.html" %}
                <div class="accordion">
                    {% for group in groups %}
                        <div class="card">
                            <a class="card-toggle" href="#">{{ group.name }}</a>
                            <div class="card-body">
                                {% for tag in group.tags.all() %}
                                    <div>
                                        {{ make_tag_url(tag) }}<br>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div id="content-left" class="problems h-scrollable-table">
            <table id="tagproblem-table" class="table striped">
                <thead>
                <tr>
                    <th class="problem-code">{{ _('Problem code') }}</th>
                    <th class="problem-name">{{ _('Problem name') }}</th>
                    <th class="judge">{{ _('OJ') }}</th>
                </tr>
                </thead>
                <tbody>
                {% for problem in tagproblems %}
                {% set detail_link = url('tagproblem_detail', problem.code) %}
                    <tr>
                        <td class="problem-code">
                            <a href="{{ detail_link }}">{{ problem.code }}</a>
                        </td>
                        <td class="problem-name">
                            <div style="float: left">
                                <a href="{{ detail_link }}">{{ problem.name }}</a>
                            </div>
                            <div style="float: right" class="row-tag-list">
                                {% for tag in problem.tag.all() %}
                                    <em>{{ make_tag_url(tag) }}</em>{% if not loop.last %}, {% endif %}
                                {% endfor %}
                            </div>
                        </td>
                        <td class="judge">
                            <a href="{{ problem.link }}">{{ problem.judge }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if page_obj.has_other_pages() %}
                <div class="bottom-pagination-bar">{% include "list-pages.html" %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/tag/problem.html
{% extends "base.html" %}

{% macro make_tag_url(tag) -%}
<a href="{{ url('tagproblem_list') }}?tag_id={{ tag.code }}" tag_id={{ tag.code }}>{{ tag.name }}</a>
{%- endmacro -%}

{% block media %}
    {% include "comments/media-css.html" %}
{% endblock %}

{% block js_media %}
    {% include "comments/media-js.html" %}
{% endblock %}

{% block title_ruler %}{% endblock %}

{% block title_row %}
    <div class="problem-title">
        <div class="tabs">
            <h2>{{ content_title }}</h2>
            <span class="spacer"></span>
            <ul>
                {% if request.user.is_authenticated and request.profile.can_tag_problems %}
                    <li class="tab">
                        <a href="{{ url('tagproblem_assign', problem.code) }}"><i class="tab-icon fa fa-plus"></i>{{ _('Assign new tag') }}</a>
                    </li>
                {% endif %}
                {% if request.user.is_superuser %}
                    <li class="tab">
                        <a href="{{ url('admin:judge_tagproblem_change', problem.id) }}"><i class="tab-icon fa fa-edit"></i>{{ _('Admin') }}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block body %}
    <table id="tag-table" class="table striped">
        <thead>
            <tr>
                <th>Tag</th>
                <th>Assigner</th>
            </tr>
        <thead>
        <div class="alert alert-warning alert-dismissable">
            {{_("The problem tag might not be correct. Please feel free to leave a comment or use the report button at the top right of the navigation bar.")}}
        </div>
        <tbody>
            {% for tag in problem.tagdata_set.all() %}
                <tr>
                    <td>{{ make_tag_url(tag.tag) }}</td>
                    <td>{{ link_user(tag.assigner) }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "comments/list.html" %}
{% endblock %}

{% block bodyend %}
    {{ super() }}
    {% if REQUIRE_JAX %}
        {% include "mathjax-load.html" %}
    {% endif %}
{% endblock %}

templates/tag/search-form.html
<div class="sidebox">
    <h3>{{ _('Problem search') }} <i class="fa fa-search"></i></h3>
    <div class="sidebox-content">
        <form id="filter-form" name="form" action="" method="get">
            {% if selected_tag %}<input type="hidden" name="tag_id" value="{{ selected_tag }}">{% endif %}
            <div>
                <input id="search" type="text" name="search" value="{{ search_query or '' }}"
                        placeholder="{{ _('Search problems...') }}">
            </div>
            <div class="filter-form-group">
                <label for="judge"><i>{{ _('Online judges') }}</i></label>
                <select id="judges" name="judge" multiple>
                    {% for id, full_name in judges %}
                        <option value="{{ id }}"{% if id in selected_judges %} selected{% endif %}>
                            {{ full_name }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-submit-group">
                <a id="go" class="button">{{ _('Go') }}</a>
                <a id="random" class="button">{{ _('Random') }}</a>
                <a class="button" href="{{url('tagproblem_list')}}">{{ _('Clear search') }}</a>
            </div>
        </form>
    </div>
    <script>
        $(function () {
            var $form = $('form#filter-form');

            $('#judges').select2({
                theme: '{{ DMOJ_SELECT2_THEME }}',
                multiple: 1,
                placeholder: {{ _('Filter by online judge...')|htmltojs }},
            }).css({'visibility': 'visible'});

            $('#go').click(function () {
                $form.submit();
            });

            $('#random').click(function (e) {
                var action = $form.attr('action');
                $form.attr('action', '{{ url('tagproblem_random') }}').attr('target', '_blank').submit();
                $form.attr('action', action).attr('target', '');
                e.preventDefault();
            });
        });
    </script>
</div>

templates/tag/tag-list-tabs.html
{% extends "tabs-base.html" %}

{% block tabs %}
    {% if request.user.is_authenticated and request.user.profile.can_tag_problems %}
        {{ make_tab('create', 'fa-plus', url('tagproblem_create'), _('Create new tag problem')) }}
    {% endif %}
    {{ make_tab('list', 'fa-list', url('tagproblem_list'), _('List')) }}
    {% if request.user.is_superuser %}
        {{ make_tab('admin', 'fa-edit', url('admin:judge_tagproblem_changelist'), _('Admin')) }}
    {% endif %}
{% endblock %}